version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'prettier-plugin-tailwindcss'
      lint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'prettier*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
